from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from .models import User

@admin.register(User)
class UserAdmin(BaseUserAdmin):
    model = User

    # List display for the user changelist page
    list_display = (
        "username",
        "email",
        "phone",
        "role",
        "is_staff",
        "is_active",
        "created_at",
    )

    # Filters on the right side
    list_filter = (
        "role",
        "is_staff",
        "is_active",
        "created_at",
    )

    # Search fields
    search_fields = (
        "email",
        "phone",
        "first_name",
        "last_name",
        "username",
    )

    # Ordering of the list
    ordering = ("-created_at",)

    # Fields that cannot be edited (username is auto-generated by model logic)
    readonly_fields = (
        "id",
        "created_at",
        "updated_at",
        "username",
    )

    # Layout of the edit form
    fieldsets = (
        ("Authentication", {
            "fields": ("email", "phone", "username", "password", "google_id"),
            "classes": ("collapse",),
        }),
        ("Personal Info", {
            "fields": (
                "first_name",
                "last_name",
                "bio",
                "avatar",
            )
        }),
        ("Permissions", {
            "fields": (
                "role",
                "is_active",
                "is_staff",
                "is_superuser",
                "groups",
                "user_permissions",
            )
        }),
        ("Important Dates", {
            "fields": (
                "last_login",
                "created_at",
                "updated_at",
            )
        }),
        ("System IDs", {
            "fields": ("id",),
            "classes": ("collapse",),
        }),
    )

    # Layout of the add form
    # 'username' is included here so admins can manually set it if needed, 
    # though it usually auto-generates from email/phone.
    add_fieldsets = (
        (None, {
            "classes": ("wide",),
            "fields": (
                "email",
                "phone",
                "username",
                "password1",
                "password2",
                "role",
                "is_active",
                "is_staff",
            ),
        }),
    )

# Note: PasswordResetToken and EmailVerificationCode admins were removed 
# because their models were removed in the database schema update.