import type { Crop } from "../domain/entities/Crop";

export const CROPS: Crop[] = [
  {
    id: "wheat",
    name: "Wheat",
    nameAr: "القمح",
    nameFr: "Blé",
    category: "grain",
    image: "https://images.unsplash.com/photo-1501430654243-c934cec2e1c0?w=600&h=400&fit=crop",
    rating: 4.8,
    description: "The most widely cultivated cereal in Algeria. Durum wheat represents about 45% of the cereal area, while soft wheat is 15%. Adapted to the High Plateaux and Mediterranean zones.",
    plantingSeason: "Oct - Dec",
    harvestSeason: "May - Jul",
    waterNeeds: "450-650 mm/cycle (Mainly rainfed)",
    soilType: "Loamy, well-drained",
    diseases: ["Brown Rust (الصدأ البني)", "Septoria (السبتوريوز)", "Powdery Mildew (البياض الدقيقي)"],
    funFact: "Algeria's national average yield is around 17 q/ha, but irrigated areas can reach up to 72 q/ha.",
    yieldAverage: "16-20 q/ha",
    yieldPotential: "30-40 q/ha"
  },
  {
    id: "barley",
    name: "Barley",
    nameAr: "الشعير",
    nameFr: "Orge",
    category: "grain",
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&h=400&fit=crop",
    rating: 4.5,
    description: "More rustic than wheat, better adapted to semi-arid zones. Represents about 33% of the Algerian cereal area.",
    plantingSeason: "Oct - Dec",
    harvestSeason: "May - Jun",
    waterNeeds: "350-500 mm/cycle",
    soilType: "Sandy loam, saline tolerant",
    diseases: ["Dwarf Rust (الصدأ القزم)", "Net Blotch (تبقع الأوراق)", "Loose Smut (التفحم السائب)"],
    funFact: "Barley can grow in high plains where wheat cannot survive the drought.",
    yieldAverage: "13-15 q/ha",
    yieldPotential: "Up to 50 q/ha irrigated"
  },
  {
    id: "tomato",
    name: "Tomato",
    nameAr: "طماطم",
    nameFr: "Tomate",
    category: "vegetable",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&h=400&fit=crop",
    rating: 4.9,
    description: "Industrial tomatoes are grown primarily in Chlef, Skikda, and Annaba. Greenhouse tomatoes in Biskra provide winter primeurs.",
    plantingSeason: "Jan - Mar",
    harvestSeason: "Jun - Sep",
    waterNeeds: "4000-5000 m3/ha (5 mm/day)",
    soilType: "Loamy, rich in organic matter",
    diseases: ["Late Blight (البياض الزغبي)", "Tuta absoluta (حافرة أوراق)", "Whitefly (الذبابة البيضاء)"],
    funFact: "Greenhouse tomatoes in Biskra can exceed yields of 100 tons per hectare.",
    yieldAverage: "50-70 t/ha (Open field)",
    yieldPotential: "100+ t/ha (Greenhouse)"
  },
  {
    id: "olive",
    name: "Olive",
    nameAr: "زيتون",
    nameFr: "Olivier",
    category: "tree_crop",
    image: "https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=600&h=400&fit=crop",
    rating: 5.2,
    description: "Algeria is the 9th largest olive oil producer globally. Cultivation is prominent in Béjaïa, Tizi Ouzou, and Bouira.",
    plantingSeason: "Feb - Apr",
    harvestSeason: "Oct - Feb",
    waterNeeds: "400-800 mm/year",
    soilType: "Rocky, calcareous",
    diseases: ["Peacock Spot (عين الطاووس)", "Olive Fly (ذبابة الزيتون)", "Verticillium Wilt (ذبول الفرتيسيليوم)"],
    funFact: "Some Algerian olive trees are over 1,000 years old, experiencing heavy alternate bearing seasons.",
    yieldAverage: "15-30 kg/tree",
    yieldPotential: "50-65 kg/tree (Intensive)"
  },
  {
    id: "date_palm",
    name: "Date Palm",
    nameAr: "نخيل التمر",
    nameFr: "Palmier dattier",
    category: "tree_crop",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop",
    rating: 5.8,
    description: "The iconic fruit of the Algerian Sahara. Deglet Nour is the primary variety. Thrives in Biskra, El Oued, and Ouargla.",
    plantingSeason: "Feb - Apr",
    harvestSeason: "Sep - Nov",
    waterNeeds: "1500-2500 mm/year (200-300 L/tree/day in summer)",
    soilType: "Sandy, saline",
    diseases: ["Bayoud (البيوض)", "Boufaroua (بوفروة)", "Date Moth (دودة التمر)"],
    funFact: "Algeria produces ~1.1 million tons of dates annually.",
    yieldAverage: "15-30 kg/tree",
    yieldPotential: "50-60 kg/tree"
  },
  {
    id: "potato",
    name: "Potato",
    nameAr: "بطاطا",
    nameFr: "Pomme de terre",
    category: "vegetable",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82ber40f?w=600&h=400&fit=crop",
    rating: 5.0,
    description: "Grown in three seasons in Algeria: primeur, season, and late season. Crucial crop in Mascara, El Oued, and Aïn Defla.",
    plantingSeason: "Feb - Apr / Aug - Sep",
    harvestSeason: "Jun - Jul / Nov - Dec",
    waterNeeds: "500-700 mm/cycle",
    soilType: "Sandy loam, well-drained",
    diseases: ["Late Blight (البياض الزغبي)", "Early Blight (تبقع الأوراق)", "Bacterial Wilt (الذبول البكتيري)"],
    funFact: "Algeria produces over 4.2 million tons of potatoes per year.",
    yieldAverage: "25-30 t/ha",
    yieldPotential: "40+ t/ha"
  },
  {
    id: "onion",
    name: "Onion",
    nameAr: "بصل",
    nameFr: "Oignon",
    category: "vegetable",
    image: "https://images.unsplash.com/photo-1618512496248-a07ce83ab811?w=600&h=400&fit=crop",
    rating: 4.6,
    description: "A major vegetable crop in Algeria, highly dependent on photoperiod for bulbing. Grown heavily in Tiaret and Mascara.",
    plantingSeason: "Sep - Oct / Jan - Mar",
    harvestSeason: "Apr - Jul",
    waterNeeds: "350-550 mm/cycle",
    soilType: "Loamy, well-drained",
    diseases: ["Downy Mildew (البياض الزغبي)", "Botrytis (العفن الرمادي)", "Thrips (التريبس)"],
    funFact: "Algeria is among the top 10 global onion producers, yielding up to 1.76 million tons.",
    yieldAverage: "30-60 t/ha",
    yieldPotential: "100+ t/ha (Modern irrigated)"
  },
  {
    id: "pepper",
    name: "Pepper",
    nameAr: "فلفل",
    nameFr: "Poivron / Piment",
    category: "vegetable",
    image: "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=600&h=400&fit=crop",
    rating: 4.7,
    description: "Cultivated both in open fields and greenhouses (especially in Biskra for winter production). Used fresh and for Harissa.",
    plantingSeason: "Feb - Mar",
    harvestSeason: "Jun - Oct",
    waterNeeds: "600-900 mm/cycle",
    soilType: "Rich loam",
    diseases: ["Blight (البياض الزغبي)", "Spider Mites (العناكب الحمراء)", "Tuta absoluta (حافرة الأوراق)"],
    funFact: "Peppers require 4-6 mm of daily water from flowering to harvest.",
    yieldAverage: "26 t/ha",
    yieldPotential: "60+ t/ha (Greenhouse)"
  },
  {
    id: "watermelon",
    name: "Watermelon",
    nameAr: "دلاع",
    nameFr: "Pastèque",
    category: "vegetable",
    image: "https://images.unsplash.com/photo-1587049352847-4d4b12421376?w=600&h=400&fit=crop",
    rating: 4.9,
    description: "Production is booming in the south (El Oued) using multi-span greenhouses for early harvest. Often grafted onto pumpkin rootstocks.",
    plantingSeason: "Jan - Mar (South) / Apr - Jun (North)",
    harvestSeason: "May - Sep",
    waterNeeds: "400-600 mm/cycle",
    soilType: "Sandy, well-drained",
    diseases: ["Fusarium Wilt (ذبول الفيوزاريوم)", "Anthracnose (الأنثراكنوز)", "Downy Mildew (البياض الزغبي)"],
    funFact: "Grafted watermelons in El Oued greenhouses can reach 120 tons per hectare.",
    yieldAverage: "40-60 t/ha",
    yieldPotential: "120 t/ha (Grafted)"
  },
  {
    id: "citrus",
    name: "Citrus",
    nameAr: "حمضيات",
    nameFr: "Agrumes",
    category: "tree_crop",
    image: "https://images.unsplash.com/photo-1517260739337-6799d239ce83?w=600&h=400&fit=crop",
    rating: 5.1,
    description: "Algeria's Mediterranean coast is ideal for citrus. Oranges (Maroc Late, Thomson Navel) make up 67% of the area, primarily in Blida.",
    plantingSeason: "Feb - Apr",
    harvestSeason: "Nov - Apr",
    waterNeeds: "800-1200 mm/year",
    soilType: "Deep loam, slightly acidic",
    diseases: ["Citrus Tristeza (تريستيزا الحمضيات)", "Mal Secco (المال سيكو)", "Scale Insects (الحشرات القشرية)"],
    funFact: "Algeria produces about 1.8 million tons of citrus across 80,000 hectares.",
    yieldAverage: "20-25 t/ha",
    yieldPotential: "40+ t/ha (Intensive)"
  }
];

export const CATEGORIES = [
  { id: "all", label: "All", labelAr: "الكل", labelFr: "Tout" },
  { id: "tree_crop", label: "Trees", labelAr: "أشجار", labelFr: "Arbres" },
  { id: "grain", label: "Grain", labelAr: "حبوب", labelFr: "Céréales" },
  { id: "vegetable", label: "Vegetable", labelAr: "خضار", labelFr: "Légumes" },
];
