from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from django.conf import settings
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from Auth.permissions import IsFarmer
from .models import FieldLog, WeatherAlert
from .utils import (
    fetch_weather,
    get_user_location,
    parse_weather_conditions,
    generate_intelligent_alert,
)


log_body = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    required=['crop', 'action_type', 'date'],
    properties={
        'crop': openapi.Schema(type=openapi.TYPE_STRING, example='blé'),
        'action_type': openapi.Schema(
            type=openapi.TYPE_STRING,
            enum=['watering', 'treatment', 'planting', 'harvesting', 'fertilizing', 'observation']
        ),
        'date': openapi.Schema(type=openapi.TYPE_STRING, format='date', example='2026-04-27'),
        'notes': openapi.Schema(type=openapi.TYPE_STRING, example='Application fongicide parcelle nord.'),
        'lat': openapi.Schema(type=openapi.TYPE_NUMBER, example=36.365, description='Optional — auto-detected if not provided.'),
        'lon': openapi.Schema(type=openapi.TYPE_NUMBER, example=6.614, description='Optional — auto-detected if not provided.'),
    }
)

log_response = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    properties={
        'id': openapi.Schema(type=openapi.TYPE_INTEGER),
        'crop': openapi.Schema(type=openapi.TYPE_STRING),
        'action_type': openapi.Schema(type=openapi.TYPE_STRING),
        'date': openapi.Schema(type=openapi.TYPE_STRING, format='date'),
        'notes': openapi.Schema(type=openapi.TYPE_STRING),
        'created_at': openapi.Schema(type=openapi.TYPE_STRING, format='date-time'),
    }
)


class FieldLogListView(APIView):
    permission_classes = [IsFarmer]

    @swagger_auto_schema(
        operation_summary="List all field logs for the current farmer",
        manual_parameters=[
            openapi.Parameter('crop', openapi.IN_QUERY, type=openapi.TYPE_STRING, required=False),
            openapi.Parameter('action_type', openapi.IN_QUERY, type=openapi.TYPE_STRING, required=False),
        ],
        responses={
            200: openapi.Response('Field logs', openapi.Schema(type=openapi.TYPE_ARRAY, items=log_response)),
            401: 'Unauthorized',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def get(self, request):
        qs = FieldLog.objects.filter(user=request.user).order_by('-date')

        crop = request.query_params.get('crop')
        action_type = request.query_params.get('action_type')

        if crop:
            qs = qs.filter(crop__icontains=crop)
        if action_type:
            qs = qs.filter(action_type=action_type)

        data = [
            {
                'id': log.id,
                'crop': log.crop,
                'action_type': log.action_type,
                'date': log.date,
                'notes': log.notes,
                'created_at': log.created_at,
            }
            for log in qs
        ]
        return Response(data, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_summary="Create a new field log",
        operation_description=(
            "Logs a farm intervention. Location is auto-detected from IP if lat/lon not provided. "
            "An intelligent weather alert is generated by Grok AI if conditions are dangerous for the logged action."
        ),
        request_body=log_body,
        responses={
            201: openapi.Response('Log created', openapi.Schema(
                type=openapi.TYPE_OBJECT,
                properties={
                    'id': openapi.Schema(type=openapi.TYPE_INTEGER),
                    'message': openapi.Schema(type=openapi.TYPE_STRING),
                    'alerts': openapi.Schema(
                        type=openapi.TYPE_ARRAY,
                        items=openapi.Schema(type=openapi.TYPE_STRING),
                        nullable=True,
                        description='AI-generated weather alerts in the farmer language, or null.'
                    ),
                }
            )),
            400: 'Missing required fields',
            401: 'Unauthorized',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def post(self, request):
        crop = request.data.get('crop', '').strip()
        action_type = request.data.get('action_type', '').strip()
        date = request.data.get('date')
        notes = request.data.get('notes', '')
        lat = request.data.get('lat')
        lon = request.data.get('lon')

        if not crop or not action_type or not date:
            return Response(
                {'error': 'crop, action_type, and date are required.'},
                status=status.HTTP_400_BAD_REQUEST
            )

        valid_actions = ['watering', 'treatment', 'planting', 'harvesting', 'fertilizing', 'observation']
        if action_type not in valid_actions:
            return Response(
                {'error': f'Invalid action_type. Must be one of: {", ".join(valid_actions)}'},
                status=status.HTTP_400_BAD_REQUEST
            )

        log = FieldLog.objects.create(
            user=request.user,
            crop=crop,
            action_type=action_type,
            date=date,
            notes=notes,
        )

        alert_messages = []

        try:
            if lat and lon:
                resolved_lat, resolved_lon = float(lat), float(lon)
            else:
                resolved_lat, resolved_lon = get_user_location()

            if resolved_lat and resolved_lon:
                weather_data = fetch_weather(resolved_lat, resolved_lon)
                conditions = parse_weather_conditions(weather_data)

                alert_text = generate_intelligent_alert(
                    crop=crop,
                    action_type=action_type,
                    notes=notes,
                    weather_conditions=conditions,
                    api_key=settings.GROQ_API_KEY,
                )

                if alert_text:
                    alert_type = "rain"
                    if conditions.get("heat_alert"):
                        alert_type = "heat"
                    elif conditions.get("frost_alert"):
                        alert_type = "frost"
                    elif conditions.get("wind_alert"):
                        alert_type = "wind"

                    WeatherAlert.objects.create(
                        user=request.user,
                        field_log=log,
                        alert_type=alert_type,
                        message=alert_text,
                    )
                    alert_messages.append(alert_text)

        except (ValueError, TypeError):
            pass

        return Response({
            'id': log.id,
            'message': 'Field log created.',
            'alerts': alert_messages if alert_messages else None,
        }, status=status.HTTP_201_CREATED)


class FieldLogDetailView(APIView):
    permission_classes = [IsFarmer]

    @swagger_auto_schema(
        operation_summary="Get a single field log",
        responses={
            200: openapi.Response('Field log', log_response),
            401: 'Unauthorized',
            404: 'Not found',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def get(self, request, pk):
        log = get_object_or_404(FieldLog, pk=pk, user=request.user)
        return Response({
            'id': log.id,
            'crop': log.crop,
            'action_type': log.action_type,
            'date': log.date,
            'notes': log.notes,
            'created_at': log.created_at,
            'updated_at': log.updated_at,
        }, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_summary="Update a field log",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                'crop': openapi.Schema(type=openapi.TYPE_STRING),
                'action_type': openapi.Schema(type=openapi.TYPE_STRING),
                'date': openapi.Schema(type=openapi.TYPE_STRING, format='date'),
                'notes': openapi.Schema(type=openapi.TYPE_STRING),
            }
        ),
        responses={
            200: 'Updated',
            401: 'Unauthorized',
            404: 'Not found',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def patch(self, request, pk):
        log = get_object_or_404(FieldLog, pk=pk, user=request.user)
        for field in ['crop', 'action_type', 'date', 'notes']:
            if field in request.data:
                setattr(log, field, request.data[field])
        log.save()
        return Response({'message': 'Field log updated.'}, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_summary="Delete a field log",
        responses={
            204: 'Deleted',
            401: 'Unauthorized',
            404: 'Not found',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def delete(self, request, pk):
        log = get_object_or_404(FieldLog, pk=pk, user=request.user)
        log.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class WeatherAlertListView(APIView):
    permission_classes = [IsFarmer]

    @swagger_auto_schema(
        operation_summary="Get all weather alerts for the current farmer",
        operation_description="Returns all AI-generated alerts for the farmer's logs. Unread alerts appear first.",
        responses={
            200: openapi.Response('Alerts', openapi.Schema(
                type=openapi.TYPE_ARRAY,
                items=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'id': openapi.Schema(type=openapi.TYPE_INTEGER),
                        'alert_type': openapi.Schema(type=openapi.TYPE_STRING),
                        'message': openapi.Schema(type=openapi.TYPE_STRING),
                        'is_read': openapi.Schema(type=openapi.TYPE_BOOLEAN),
                        'field_log_id': openapi.Schema(type=openapi.TYPE_INTEGER),
                        'created_at': openapi.Schema(type=openapi.TYPE_STRING, format='date-time'),
                    }
                )
            )),
            401: 'Unauthorized',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def get(self, request):
        alerts = WeatherAlert.objects.filter(user=request.user).order_by('is_read', '-created_at')
        data = [
            {
                'id': a.id,
                'alert_type': a.alert_type,
                'message': a.message,
                'is_read': a.is_read,
                'field_log_id': a.field_log_id,
                'created_at': a.created_at,
            }
            for a in alerts
        ]
        return Response(data, status=status.HTTP_200_OK)


class WeatherAlertMarkReadView(APIView):
    permission_classes = [IsFarmer]

    @swagger_auto_schema(
        operation_summary="Mark a weather alert as read",
        responses={
            200: 'Marked as read',
            401: 'Unauthorized',
            404: 'Not found',
        },
        security=[{"Bearer": []}],
        tags=['Journal']
    )
    def patch(self, request, pk):
        alert = get_object_or_404(WeatherAlert, pk=pk, user=request.user)
        alert.is_read = True
        alert.save()
        return Response({'message': 'Alert marked as read.'}, status=status.HTTP_200_OK)