# Generated by Django 5.2.13 on 2026-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('crop', models.CharField(choices=[('wheat', 'Wheat'), ('tomato', 'Tomato'), ('olive', 'Olive'), ('date_palm', 'Date Palm'), ('potato', 'Potato'), ('onion', 'Onion'), ('pepper', 'Pepper'), ('watermelon', 'Watermelon'), ('citrus', 'Citrus'), ('barley', 'Barley')], max_length=20)),
                ('wilaya', models.CharField(choices=[('adrar', 'Adrar'), ('chlef', 'Chlef'), ('laghouat', 'Laghouat'), ('oum_el_bouaghi', 'Oum El Bouaghi'), ('batna', 'Batna'), ('bejaia', 'Béjaïa'), ('biskra', 'Biskra'), ('bechar', 'Béchar'), ('blida', 'Blida'), ('bouira', 'Bouira'), ('tamanrasset', 'Tamanrasset'), ('tebessa', 'Tébessa'), ('tlemcen', 'Tlemcen'), ('tiaret', 'Tiaret'), ('tizi_ouzou', 'Tizi Ouzou'), ('alger', 'Alger'), ('djelfa', 'Djelfa'), ('jijel', 'Jijel'), ('setif', 'Sétif'), ('saida', 'Saïda'), ('skikda', 'Skikda'), ('sidi_bel_abbes', 'Sidi Bel Abbès'), ('annaba', 'Annaba'), ('guelma', 'Guelma'), ('constantine', 'Constantine'), ('medea', 'Médéa'), ('mostaganem', 'Mostaganem'), ('msila', "M'Sila"), ('mascara', 'Mascara'), ('ouargla', 'Ouargla'), ('oran', 'Oran'), ('el_bayadh', 'El Bayadh'), ('illizi', 'Illizi'), ('bordj_bou_arreridj', 'Bordj Bou Arréridj'), ('boumerdes', 'Boumerdès'), ('el_tarf', 'El Tarf'), ('tindouf', 'Tindouf'), ('tissemsilt', 'Tissemsilt'), ('el_oued', 'El Oued'), ('khenchela', 'Khenchela'), ('souk_ahras', 'Souk Ahras'), ('tipaza', 'Tipaza'), ('mila', 'Mila'), ('ain_defla', 'Aïn Defla'), ('naama', 'Naâma'), ('ain_temouchent', 'Aïn Témouchent'), ('ghardaia', 'Ghardaïa'), ('relizane', 'Relizane')], max_length=50)),
                ('disease_tag', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
