# Generated by Django 5.2.13 on 2026-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropFactSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('planting_calendar', models.JSONField(help_text="e.g. {'sow': ['Oct','Nov'], 'harvest': ['May','Jun']}")),
                ('water_needs', models.JSONField(help_text="e.g. {'liters_per_m2_per_week': 25, 'notes_fr': '...', 'notes_ar': '...'}")),
                ('avg_yield', models.CharField(max_length=120)),
                ('description_fr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('symptoms_fr', models.TextField()),
                ('symptoms_ar', models.TextField()),
                ('treatment_fr', models.TextField()),
                ('treatment_ar', models.TextField()),
                ('prevention_fr', models.TextField(blank=True)),
                ('prevention_ar', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_crops', models.ManyToManyField(blank=True, related_name='common_diseases', to='offline_content.cropfactsheet')),
            ],
            options={
                'ordering': ['name_fr'],
            },
        ),
    ]
