# Generated by Django 5.2.13 on 2026-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer')], default='farmer', max_length=10),
        ),
    ]
