# Generated by Django 5.2.13 on 2026-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
